spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/examplesdb?useUnicode=true&serverTimezone=Asia/Seoul
    username: urstory
    password: u1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      database-platform : org.hibernate.dialect.MySQL8Dialect
    profiles:
      active: local
  logging:
    output:
      ansi:
        enabled: always
jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012
